const data = {
  products: [
    {
      _id:'1',
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      categories: "shirts",
      image: "/image/p.jpg",
      price: 120,
      countInstock: 10,
      brand: "Nike",
      Rating: 4.5,
      numReviews: 10,
      desc: "high quality shirt",
    },
    {
      _id:'2',
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      categories: "adidas",
      image: "/image/p1.jpg",
      price: 320,
      countInstock: 10,
      brand: "adidas",
      Rating: 4.0,
      numReviews: 10,
      desc: "high quality shirt",
    },
    {
      _id:'3',
      name: "Nike SlikPant",
      slug: "nike-slim-pant",
      categories: "pants",
      image: "/image/p2.avif",
      price: 25,
      countInstock: 15,
      brand: "Nike",
      Rating: 4.5,
      numReviews: 15,
      desc: "high quality product",
    },
    {
      _id:'4',
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      categories: "pants",
      image: "/image/p4.jpg",
      price: 65,
      countInstock: 5,
      brand: "puma",
      Rating: 4.5,
      numReviews: 10,
      desc: "high quality product",
    },
  ],
};
export default data;
